### ISSUE TITLE
Sample App doesn't work in Windows Environment

### ISSUE THREAD

**Issue by aravindsg** [electrode-io/movielist-miniapp#15]
ern run-android
 ___ _        _               _       _  _      _   _
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.38.15] [Cauldron: -NONE-]

√ Starting React Native Packager [http://localhost:8081] 0s
√ Generating Composite locally 58s
  √ Generating Composite 52s
    √ Cleaning up existing composite directory 0s
    √ [1/1] Adding file:C:\code\learning\electrode\MovieListMiniApp 47s
  √ Syncing https://github.com/electrode-io/electrode-native-manifest.git Manifest 2s
Generating Container locally 0s
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\<user>\.ern\versions\0.38.15\node_modules\ern-core\node_modules\.bin\yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\<user>\\.ern\\versions\\0.38.15\\node_modules\\ern-core\\node_modules\\.bin\\yarn',  path: 'C:\\Users\\<user>\\.ern\\versions\\0.38.15\\node_modules\\ern-core\\node_modules\\.bin\\yarn',
  spawnargs: [ 'info', 'react-native-electrode-bridge', 'ern', '--json' ]
}

**Comment by chc7042** [comment]
Hi @aravindsg  spawn error could be fixed by change nodejs version. but after change version of nodejs
another problem occur at this time did you solve this problem?
