### ISSUE TITLE
Crash app when press a movie in list 

### ISSUE THREAD

**Issue by minh195** [electrode-io/movielist-miniapp#24]
com.walmartlabs.ern.movielistminiapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.walmartlabs.ern.movielistminiapp, PID: 19650
    java.lang.RuntimeException: Unable to pause activity {com.walmartlabs.ern.movielistminiapp/com.walmartlabs.ern.container.miniapps.MovieListMiniAppActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.ReactDelegate.onHostPause()' on a null object reference
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4531)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4482)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4434)
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7386)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.ReactDelegate.onHostPause()' on a null object reference
        at com.facebook.react.ReactActivityDelegate.onPause(ReactActivityDelegate.java:95)
        at com.walmartlabs.ern.container.ElectrodeReactActivityDelegate.onPause(ElectrodeReactActivityDelegate.java:228)
        at com.walmartlabs.ern.container.ElectrodeMiniAppActivity.onPause(ElectrodeMiniAppActivity.java:69)
        at android.app.Activity.performPause(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1507)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4521)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4482) 
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4434) 
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7386) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by quanghoang0101** [comment]
The issue from my side.
`
E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    java.lang.IllegalArgumentException: Unable to generate a Bridgeable from bundle: Bundle[{miniAppName=MovieDetailsMiniApp, initialPayload={"releaseYear":2008,"title":"The Dark Knight","id":"4","imageUrl":"http://bit.ly/2iZPBqw","rating":4,"isSelect":true}}]
        at com.walmartlabs.electrode.reactnative.bridge.util.BridgeArguments.objectFromBundle(BridgeArguments.java:304)
        at com.walmartlabs.electrode.reactnative.bridge.util.BridgeArguments.generateObject(BridgeArguments.java:197)
        at com.walmartlabs.electrode.reactnative.bridge.RequestHandlerProcessor$1.onRequest(RequestHandlerProcessor.java:68)
        at com.walmartlabs.electrode.reactnative.bridge.RequestHandlerProcessor$1.onRequest(RequestHandlerProcessor.java:54)
        at com.walmartlabs.electrode.reactnative.bridge.RequestDispatcherImpl.dispatchRequest(RequestDispatcherImpl.java:49)
        at com.walmartlabs.electrode.reactnative.bridge.ElectrodeBridgeTransceiver.dispatchRequestToLocalHandler(ElectrodeBridgeTransceiver.java:303)
        at com.walmartlabs.electrode.reactnative.bridge.ElectrodeBridgeTransceiver.handleRequest(ElectrodeBridgeTransceiver.java:268)
        at com.walmartlabs.electrode.reactnative.bridge.ElectrodeBridgeTransceiver.sendMessage(ElectrodeBridgeTransceiver.java:236)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:1012)`
